php:
    build: .
    ports:
     - "8080:80"
     - "8443:443"
    volumes:
     - ./www:/var/www/html
    links:
     - db
db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=phprs
     - MYSQL_DATABASE=phprs